import type { TokenKind } from './tokens'

export type BasicTokenDefinition = {
  readonly byte: number
  readonly kind: TokenKind
  readonly text: string
}

export const spectrumTokenDefinitions = [
  { byte: 0xa5, kind: 'RND', text: 'RND' },
  { byte: 0xa6, kind: 'INKEY', text: 'INKEY$' },
  { byte: 0xa7, kind: 'PI', text: 'PI' },
  { byte: 0xa8, kind: 'FN', text: 'FN' },
  { byte: 0xa9, kind: 'POINT', text: 'POINT' },
  { byte: 0xaa, kind: 'SCREEN', text: 'SCREEN$' },
  { byte: 0xab, kind: 'ATTR', text: 'ATTR' },
  { byte: 0xac, kind: 'AT', text: 'AT' },
  { byte: 0xad, kind: 'TAB', text: 'TAB' },
  { byte: 0xae, kind: 'VAL_STR', text: 'VAL$' },
  { byte: 0xaf, kind: 'CODE', text: 'CODE' },
  { byte: 0xb0, kind: 'VAL', text: 'VAL' },
  { byte: 0xb1, kind: 'LEN', text: 'LEN' },
  { byte: 0xb2, kind: 'SIN', text: 'SIN' },
  { byte: 0xb3, kind: 'COS', text: 'COS' },
  { byte: 0xb4, kind: 'TAN', text: 'TAN' },
  { byte: 0xb5, kind: 'ASN', text: 'ASN' },
  { byte: 0xb6, kind: 'ACS', text: 'ACS' },
  { byte: 0xb7, kind: 'ATN', text: 'ATN' },
  { byte: 0xb8, kind: 'LN', text: 'LN' },
  { byte: 0xb9, kind: 'EXP', text: 'EXP' },
  { byte: 0xba, kind: 'INT', text: 'INT' },
  { byte: 0xbb, kind: 'SQR', text: 'SQR' },
  { byte: 0xbc, kind: 'SGN', text: 'SGN' },
  { byte: 0xbd, kind: 'ABS', text: 'ABS' },
  { byte: 0xbe, kind: 'PEEK', text: 'PEEK' },
  { byte: 0xbf, kind: 'IN', text: 'IN' },
  { byte: 0xc0, kind: 'USR', text: 'USR' },
  { byte: 0xc1, kind: 'STR', text: 'STR$' },
  { byte: 0xc2, kind: 'CHR', text: 'CHR$' },
  { byte: 0xc3, kind: 'NOT', text: 'NOT' },
  { byte: 0xc4, kind: 'BIN', text: 'BIN' },
  { byte: 0xc5, kind: 'OR', text: 'OR' },
  { byte: 0xc6, kind: 'AND', text: 'AND' },
  { byte: 0xc7, kind: 'LESSEQ', text: '<=' },
  { byte: 0xc8, kind: 'GREATEQ', text: '>=' },
  { byte: 0xc9, kind: 'NOTEQ', text: '<>' },
  { byte: 0xca, kind: 'LINE', text: 'LINE' },
  { byte: 0xcb, kind: 'THEN', text: 'THEN' },
  { byte: 0xcc, kind: 'TO', text: 'TO' },
  { byte: 0xcd, kind: 'STEP', text: 'STEP' },
  { byte: 0xce, kind: 'DEFFN', text: 'DEF FN' },
  { byte: 0xcf, kind: 'CAT', text: 'CAT' },
  { byte: 0xd0, kind: 'FORMAT', text: 'FORMAT' },
  { byte: 0xd1, kind: 'MOVE', text: 'MOVE' },
  { byte: 0xd2, kind: 'ERASE', text: 'ERASE' },
  { byte: 0xd3, kind: 'OPEN', text: 'OPEN #' },
  { byte: 0xd4, kind: 'CLOSE', text: 'CLOSE #' },
  { byte: 0xd5, kind: 'MERGE', text: 'MERGE' },
  { byte: 0xd6, kind: 'VERIFY', text: 'VERIFY' },
  { byte: 0xd7, kind: 'BEEP', text: 'BEEP' },
  { byte: 0xd8, kind: 'CIRCLE', text: 'CIRCLE' },
  { byte: 0xd9, kind: 'INK', text: 'INK' },
  { byte: 0xda, kind: 'PAPER', text: 'PAPER' },
  { byte: 0xdb, kind: 'FLASH', text: 'FLASH' },
  { byte: 0xdc, kind: 'BRIGHT', text: 'BRIGHT' },
  { byte: 0xdd, kind: 'INVERSE', text: 'INVERSE' },
  { byte: 0xde, kind: 'OVER', text: 'OVER' },
  { byte: 0xdf, kind: 'OUT', text: 'OUT' },
  { byte: 0xe0, kind: 'LPRINT', text: 'LPRINT' },
  { byte: 0xe1, kind: 'LLIST', text: 'LLIST' },
  { byte: 0xe2, kind: 'STOP', text: 'STOP' },
  { byte: 0xe3, kind: 'READ', text: 'READ' },
  { byte: 0xe4, kind: 'DATA', text: 'DATA' },
  { byte: 0xe5, kind: 'RESTORE', text: 'RESTORE' },
  { byte: 0xe6, kind: 'NEW', text: 'NEW' },
  { byte: 0xe7, kind: 'BORDER', text: 'BORDER' },
  { byte: 0xe8, kind: 'CONTINUE', text: 'CONTINUE' },
  { byte: 0xe9, kind: 'DIM', text: 'DIM' },
  { byte: 0xea, kind: 'REM', text: 'REM' },
  { byte: 0xeb, kind: 'FOR', text: 'FOR' },
  { byte: 0xec, kind: 'GOTO', text: 'GO TO' },
  { byte: 0xed, kind: 'GOSUB', text: 'GO SUB' },
  { byte: 0xee, kind: 'INPUT', text: 'INPUT' },
  { byte: 0xef, kind: 'LOAD', text: 'LOAD' },
  { byte: 0xf0, kind: 'LIST', text: 'LIST' },
  { byte: 0xf1, kind: 'LET', text: 'LET' },
  { byte: 0xf2, kind: 'PAUSE', text: 'PAUSE' },
  { byte: 0xf3, kind: 'NEXT', text: 'NEXT' },
  { byte: 0xf4, kind: 'POKE', text: 'POKE' },
  { byte: 0xf5, kind: 'PRINT', text: 'PRINT' },
  { byte: 0xf6, kind: 'PLOT', text: 'PLOT' },
  { byte: 0xf7, kind: 'RUN', text: 'RUN' },
  { byte: 0xf8, kind: 'SAVE', text: 'SAVE' },
  { byte: 0xf9, kind: 'RANDOMIZE', text: 'RANDOMIZE' },
  { byte: 0xfa, kind: 'IF', text: 'IF' },
  { byte: 0xfb, kind: 'CLS', text: 'CLS' },
  { byte: 0xfc, kind: 'DRAW', text: 'DRAW' },
  { byte: 0xfd, kind: 'CLEAR', text: 'CLEAR' },
  { byte: 0xfe, kind: 'RETURN', text: 'RETURN' },
  { byte: 0xff, kind: 'COPY', text: 'COPY' },
] satisfies readonly BasicTokenDefinition[]

export const ts2068ExtensionTokenDefinitions = [
  { byte: 0x0c, kind: 'DELETE', text: 'DELETE' },
  { byte: 0x7b, kind: 'ONERR', text: 'ON ERR' },
  { byte: 0x7c, kind: 'STICK', text: 'STICK' },
  { byte: 0x7d, kind: 'SOUND', text: 'SOUND' },
  { byte: 0x7e, kind: 'FREE', text: 'FREE' },
  { byte: 0x7f, kind: 'RESET', text: 'RESET' },
] satisfies readonly BasicTokenDefinition[]

export const zx81TokenDefinitions = [
  { byte: 0x40, kind: 'RND', text: 'RND' },
  { byte: 0x41, kind: 'INKEY', text: 'INKEY$' },
  { byte: 0x42, kind: 'PI', text: 'PI' },
  { byte: 0xc1, kind: 'AT', text: 'AT' },
  { byte: 0xc2, kind: 'TAB', text: 'TAB' },
  { byte: 0xc4, kind: 'CODE', text: 'CODE' },
  { byte: 0xc5, kind: 'VAL', text: 'VAL' },
  { byte: 0xc6, kind: 'LEN', text: 'LEN' },
  { byte: 0xc7, kind: 'SIN', text: 'SIN' },
  { byte: 0xc8, kind: 'COS', text: 'COS' },
  { byte: 0xc9, kind: 'TAN', text: 'TAN' },
  { byte: 0xca, kind: 'ASN', text: 'ASN' },
  { byte: 0xcb, kind: 'ACS', text: 'ACS' },
  { byte: 0xcc, kind: 'ATN', text: 'ATN' },
  { byte: 0xcd, kind: 'LN', text: 'LN' },
  { byte: 0xce, kind: 'EXP', text: 'EXP' },
  { byte: 0xcf, kind: 'INT', text: 'INT' },
  { byte: 0xd0, kind: 'SQR', text: 'SQR' },
  { byte: 0xd1, kind: 'SGN', text: 'SGN' },
  { byte: 0xd2, kind: 'ABS', text: 'ABS' },
  { byte: 0xd3, kind: 'PEEK', text: 'PEEK' },
  { byte: 0xd4, kind: 'USR', text: 'USR' },
  { byte: 0xd5, kind: 'STR', text: 'STR$' },
  { byte: 0xd6, kind: 'CHR', text: 'CHR$' },
  { byte: 0xd7, kind: 'NOT', text: 'NOT' },
  { byte: 0xd8, kind: 'EXPON', text: '**' },
  { byte: 0xd9, kind: 'OR', text: 'OR' },
  { byte: 0xda, kind: 'AND', text: 'AND' },
  { byte: 0xdb, kind: 'LESSEQ', text: '<=' },
  { byte: 0xdc, kind: 'GREATEQ', text: '>=' },
  { byte: 0xdd, kind: 'NOTEQ', text: '<>' },
  { byte: 0xde, kind: 'THEN', text: 'THEN' },
  { byte: 0xdf, kind: 'TO', text: 'TO' },
  { byte: 0xe0, kind: 'STEP', text: 'STEP' },
  { byte: 0xe1, kind: 'LPRINT', text: 'LPRINT' },
  { byte: 0xe2, kind: 'LLIST', text: 'LLIST' },
  { byte: 0xe3, kind: 'STOP', text: 'STOP' },
  { byte: 0xe4, kind: 'SLOW', text: 'SLOW' },
  { byte: 0xe5, kind: 'FAST', text: 'FAST' },
  { byte: 0xe6, kind: 'NEW', text: 'NEW' },
  { byte: 0xe7, kind: 'SCROLL', text: 'SCROLL' },
  { byte: 0xe8, kind: 'CONTINUE', text: 'CONT' },
  { byte: 0xe9, kind: 'DIM', text: 'DIM' },
  { byte: 0xea, kind: 'REM', text: 'REM' },
  { byte: 0xeb, kind: 'FOR', text: 'FOR' },
  { byte: 0xec, kind: 'GOTO', text: 'GOTO' },
  { byte: 0xed, kind: 'GOSUB', text: 'GOSUB' },
  { byte: 0xee, kind: 'INPUT', text: 'INPUT' },
  { byte: 0xef, kind: 'LOAD', text: 'LOAD' },
  { byte: 0xf0, kind: 'LIST', text: 'LIST' },
  { byte: 0xf1, kind: 'LET', text: 'LET' },
  { byte: 0xf2, kind: 'PAUSE', text: 'PAUSE' },
  { byte: 0xf3, kind: 'NEXT', text: 'NEXT' },
  { byte: 0xf4, kind: 'POKE', text: 'POKE' },
  { byte: 0xf5, kind: 'PRINT', text: 'PRINT' },
  { byte: 0xf6, kind: 'PLOT', text: 'PLOT' },
  { byte: 0xf7, kind: 'RUN', text: 'RUN' },
  { byte: 0xf8, kind: 'SAVE', text: 'SAVE' },
  { byte: 0xf9, kind: 'RANDOMIZE', text: 'RAND' },
  { byte: 0xfa, kind: 'IF', text: 'IF' },
  { byte: 0xfb, kind: 'CLS', text: 'CLS' },
  { byte: 0xfc, kind: 'UNPLOT', text: 'UNPLOT' },
  { byte: 0xfd, kind: 'CLEAR', text: 'CLEAR' },
  { byte: 0xfe, kind: 'RETURN', text: 'RETURN' },
  { byte: 0xff, kind: 'COPY', text: 'COPY' },
] satisfies readonly BasicTokenDefinition[]

export function tokenByteMap(definitions: readonly BasicTokenDefinition[]): Partial<Record<TokenKind, number>> {
  return Object.fromEntries(definitions.map((definition) => [definition.kind, definition.byte])) as Partial<Record<TokenKind, number>>
}
