export { createPlus3DosFile, createTapFile, updateTapFileProgramEntry } from './spectrum/exportTapFile'
export type { TapEntryUpdateOptions, TapOptions } from './spectrum/exportTapFile'
export { createSpectrumWavFile } from './spectrum/exportSpectrumWavFile'
export type { WavFileOptions } from './spectrum/exportSpectrumWavFile'
export { importTapFile, importTapFileEntry, listTapFileEntries } from './spectrum/importTapFile'
export type { ImportedTapProgram, TapFileEntry, TapFileEntryType } from './spectrum/importTapFile'
export { createBasicProgramBytes, detokenizeBasicProgram } from './spectrum/spectrumBasicProgram'

export { createDockFile, updateDockFileProgramEntry } from './ts2068/exportDockFile'
export type { DockEntryUpdateOptions, DockOptions } from './ts2068/exportDockFile'
export { importDockFileEntry, listDockFileEntries } from './ts2068/importDockFile'
export type { DockFileEntry, ImportedDockProgram } from './ts2068/importDockFile'

export { createZx81PFile } from './zx81/exportPFile'
export type { PFileOptions } from './zx81/exportPFile'
export { createZx81TapeBytes, createZx81WavFile } from './zx81/exportZx81WavFile'
export type { Zx81WavFileOptions } from './zx81/exportZx81WavFile'
export { importPFile } from './zx81/importPFile'
export type { ImportedPFile, ImportedPFileSourceMapping } from './zx81/importPFile'
export { importPartialPFile } from './zx81/importPartialPFile'
export type { ImportedPartialPFile, ImportedPartialPFileLine, PartialPFileByte, PartialPFileLineStatus } from './zx81/importPartialPFile'
export { importZx81WavFile, importZx81WavPrograms } from './zx81/importZx81WavFile'
export type { DecodedZx81Wav, IZx81WavImportOptions, IZx81WavImportProgress, Zx81TapeByte, Zx81TapeSourceMapping, Zx81WavImportProgressStage } from './zx81/importZx81WavFile'
export { analyzeZx81TapeSignal } from './zx81/tape/zx81TapeSignal'
export type { IZx81TapeSignalOptions, IZx81TapeSignalProgress, Zx81TapeBit, Zx81TapeBitValue, Zx81TapeEvent, Zx81TapeEventKind, Zx81TapeSignalAnalysis, Zx81TapeSignalProgressStage, Zx81TapeSignalRegion } from './zx81/tape/zx81TapeSignal'

export { decodeWavPcm } from './common/wavPcm'
export type { WavPcmData, WavPcmProgressCallback } from './common/wavPcm'
export type { ProgramFileEntry, ProgramFileEntryType } from './common/programFileEntry'
